description: The Debian-based Docker container to use when installing SDKMS CLI
parameters:
  python-version:
    type: string
    default: "2.7"
  release:
    type: string
    default: "stretch"
docker:
  - image: circleci/python:<<parameters.python-version>>-<<parameters.release>>
